# Generated by Django 6.0.3 on 2026-04-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_active_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_active_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_country', models.CharField(max_length=100)),
                ('official_website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actresses', models.ManyToManyField(blank=True, related_name='movies', to='catalog.actress')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('scene_link', models.URLField(blank=True)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_scenes', to='catalog.actress')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actresses/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.actress')),
            ],
        ),
    ]
