# Generated by Django 6.0.3 on 2026-04-02 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedActress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_active_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_active_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
