# Generated by Django 6.0.3 on 2026-04-02 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_stagedactress'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='source_url_1280',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='StagedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file', models.ImageField(blank=True, null=True, upload_to='staged_photos/')),
                ('source_url_460', models.URLField(max_length=500)),
                ('source_url_1280', models.URLField(blank=True, max_length=500)),
                ('gallery_title', models.CharField(blank=True, max_length=300)),
                ('gallery_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_photos', to='catalog.actress')),
            ],
            options={
                'ordering': ['gallery_url', 'id'],
            },
        ),
    ]
