# Generated by Django 6.0.3 on 2026-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stagedactress_iafd_search_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='stagedphoto',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='stagedphoto',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
