# Generated by Django 6.0.3 on 2026-04-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_photo_image_hash_stagedphoto_image_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_hd',
            field=models.BooleanField(default=False),
        ),
    ]
