# Generated by Django 6.0.3 on 2026-04-05 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_actress_nationality_photo_is_hd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actress',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='favoritescene',
            options={'ordering': ['-added_at']},
        ),
        migrations.AddField(
            model_name='actress',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='actress',
            name='onlyfans_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='actress',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actress',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='favoritescene',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favoritescene',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritescene',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoritescene',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
